services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8000:8000'
        env_file:
            - .env
        volumes:
            - ./uploads:/app/uploads
        depends_on:
            - mysqldbhost

    mysqldbhost:
        image: mariadb:10.4.28
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: motorcycle_repair_shop_db
        ports:
            - '3007:3306'
        volumes:
            - mysql_data:/var/lib/mysql
            - ./motorcycle_repair_shop_db.sql:/docker-entrypoint-initdb.d/motorcycle_repair_shop_db.sql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: mysqldbhost
            PMA_USER: root
            PMA_PASSWORD: password
        ports:
            - '8080:80'
        depends_on:
            - mysqldbhost

volumes:
    mysql_data:
