services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8000:8000'
        env_file:
            - .env
        volumes:
            - ./uploads:/app/uploads
        depends_on:
            - db

    db:
        image: mysql:latest
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_DATABASE: motorcycle_repair_shop_db
            MYSQL_ROOT_HOST: '%'
        ports:
            - '3308:3306'
        volumes:
            - mysql_data:/var/lib/mysql
            - ./motorcycle_repair_shop_db.sql:/docker-entrypoint-initdb.d/motorcycle_repair_shop_db.sql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: ''
        ports:
            - '8080:80'
        depends_on:
            - db

volumes:
    mysql_data:
